name: ${project.name}
main: com.poixson.pluginlib.pxnPluginLib
version: '${project.version}'
api-version: '${bukkit-short-version}'
load: STARTUP
dependencies:
    server:
        Multiverse-Core:
            load: BEFORE
            required: false
        WorldEdit:
            load: BEFORE
            required: false
        Vault:
            load: BEFORE
            required: false
authors: lorenzop
website: ${project.url}
description: ${project.description}
permissions:
    pxn.*:
        default: op
        description: Allow all pxn plugin lib commands
        children:
            pxn.updates:           true
            pxn.cmd.help:          true
            pxn.cmd.list:          true
            pxn.cmd.home:          true
            pxn.cmd.world:         true
            pxn.cmd.world.other:   true
            pxn.cmd.spawn:         true
            pxn.cmd.spawn.other:   true
            pxn.cmd.setspawn:      true
            pxn.cmd.warp:          true
            pxn.cmd.setwarp:       true
            pxn.cmd.tp.*:          true
            pxn.cmd.back:          true
            pxn.cmd.top:           true
            pxn.cmd.bottom:        true
            pxn.cmd.jump:          true
            pxn.cmd.fly:           true
            pxn.cmd.fly.other:     true
            pxn.cmd.motd:          true
            pxn.cmd.broadcast:     true
            pxn.cmd.msg:           true
            pxn.cmd.me:            true
            pxn.cmd.gm.*:          true
            pxn.cmd.feed:          true
            pxn.cmd.feed.other:    true
            pxn.cmd.heal:          true
            pxn.cmd.heal.other:    true
            pxn.cmd.rest:          true
            pxn.cmd.rest.other:    true
            pxn.cmd.speed.*:       true
            pxn.cmd.workbench:     true
            pxn.cmd.enderchest:    true
            pxn.cmd.powertool:     true
            pxn.cmd.backup:        true
            pxn.cmd.gc:            true
            pxn.cmd.uptime:        true
    pxn.cmd.tp.*:
        default: op
        description: "Allow all commands: /tp <...>"
        children:
            pxn.cmd.tp:            true
            pxn.cmd.tp.here:       true
            pxn.cmd.tp.ask:        true
            pxn.cmd.tp.askhere:    true
            pxn.cmd.tp.allhere:    true
            pxn.cmd.tp.askallhere: true
    pxn.cmd.gm.*:
        default: op
        description: "Allow all commands: /gm <...>"
        children:
            pxn.cmd.gm:    true
            pxn.cmd.gm.c:  true
            pxn.cmd.gm.s:  true
            pxn.cmd.gm.a:  true
            pxn.cmd.gm.sp: true
    pxn.cmd.gm.other.*:
        default: op
        description: "Allow all commands: /gm <...> <player>"
        children:
            pxn.cmd.gm.other:    true
            pxn.cmd.gm.c.other:  true
            pxn.cmd.gm.s.other:  true
            pxn.cmd.gm.a.other:  true
            pxn.cmd.gm.sp.other: true
    pxn.cmd.speed.*:
        default: op
        description: "Allow commands: /walkspeed and /flyspeed"
        children:
            pxn.cmd.speed:      true
            pxn.cmd.speed.walk: true
            pxn.cmd.speed.fly:  true
    pxn.updates:
        default: op
        description: Receive notices of plugin updates.
    pxn.cmd.help:
        default: true
        description: "Allow command: /help"
    pxn.cmd.list:
        default: true
        description: "Allow command: /list"

    pxn.cmd.home:
        default: op
        description: "Allow command: /home"
    pxn.cmd.world:
        default: op
        description: "Allow command: /world <world>"
    pxn.cmd.world.other:
        default: op
        description: "Allow command: /world <world> <player>.."
    pxn.cmd.spawn:
        default: op
        description: "Allow command: /spawn"
    pxn.cmd.spawn.other:
        default: op
        description: "Allow command: /spawn <player>.."
    pxn.cmd.setspawn:
        default: op
        description: "Allow command: /setspawn"
    pxn.cmd.warp:
        default: op
        description: "Allow command: /warp"
    pxn.cmd.setwarp:
        default: op
        descroption: "Allow command: /setwarp"

    pxn.cmd.tp:
        default: op
        description: "Allow command: /tp"
    pxn.cmd.tp.here:
        default: op
        description: "Allow command: /tp-here"
    pxn.cmd.tp.ask:
        default: op
        description: "Allow command: /tp-ask"
    pxn.cmd.tp.askhere:
        default: op
        description: "Allow command: /tp-ask-here"
    pxn.cmd.tp.allhere:
        default: op
        description: "Allow command: /tp-all-here"
    pxn.cmd.tp.askallhere:
        default: op
        description: "Allow command: /tp-ask-all-here"
    pxn.cmd.tp.offline:
        default: op
        description: "Allow command: /tp-offline"

    pxn.cmd.back:
        default: op
        description: "Allow command: /back"
    pxn.cmd.top:
        default: op
        description: "Allow command: /top"
    pxn.cmd.bottom:
        default: op
        description: "Allow command: /bottom"

    pxn.cmd.jump:
        default: op
        description: "Allow command: /jump"
    pxn.cmd.fly:
        default: op
        description: "Allow command: /fly"
    pxn.cmd.fly.other:
        default: op
        description: "Allow command: /fly <player>.."

    pxn.cmd.motd:
        default: true
        description: "Allow command: /motd"
    pxn.cmd.broadcast:
        default: op
        description: "Allow command: /broadcast"
    pxn.cmd.msg:
        default: true
        description: "Allow command: /msg"
    pxn.cmd.me:
        default: true
        description: "Allow command: /me"

    pxn.cmd.gm:
        default: op
        description: "Allow command: /gm"
    pxn.cmd.gm.c:
        default: op
        description: "Allow command: /gmc"
    pxn.cmd.gm.s:
        default: op
        description: "Allow command: /gms"
    pxn.cmd.gm.a:
        default: op
        description: "Allow command: /gma"
    pxn.cmd.gm.sp:
        default: op
        description: "Allow command: /gmsp"

    pxn.cmd.feed:
        default: op
        description: "Allow command: /feed"
    pxn.cmd.feed.other:
        default: op
        description: "Allow command: /feed <player>.."
    pxn.cmd.heal:
        default: op
        description: "Allow command: /heal"
    pxn.cmd.heal.other:
        default: op
        description: "Allow command: /heal <player>.."
    pxn.cmd.rest:
        default: op
        description: "Allow command: /rest"
    pxn.cmd.rest.other:
        default: op
        description: "Allow command: /rest <player>.."

    pxn.cmd.speed:
        default: op
        description: "Allow command: /speed"
    pxn.cmd.speed.walk:
        default: op
        description: "Allow command: /walkspeed"
    pxn.cmd.speed.fly:
        default: op
        description: "Allow command: /flyspeed"

    pxn.cmd.workbench:
        default: op
        description: "Allow command: /workbench"
    pxn.cmd.enderchest:
        default: op
        description: "Allow command: /enderchest"

    pxn.cmd.powertool:
        default: op
        description: "Allow command: /powertool"
    pxn.cmd.backup:
        default: op
        description: "Allow command: /backup"
    pxn.cmd.gc:
        default: op
        description: "Allow command: /gc"
    pxn.cmd.uptime:
        default: op
        description: "Allow command: /uptime"
