name: ${project.name}
main: com.poixson.pluginlib.pxnPluginLib
version: ${project.version}
api-version: ${spigot-short-version}
load: STARTUP
softdepend:
  - Multiverse-Core
  - WorldEdit
authors: [ lorenzop ]
website: ${project.url}
description: ${project.description}
permission-message: "You don't have permission to use this command."
commands:
permissions:
    pxnpluginlib.*:
        default: op
        description: Gives access to all pxn plugin lib commands.
        children:
            pxnpluginlib.updates: true
    pxnpluginlib.updates:
        default: op
        description: Receive notices of plugin updates.
