name: ${project.name}
main: com.poixson.pluginlib.pxnPluginLib
version: ${project.version}
api-version: ${spigot-short-version}
load: STARTUP
softdepend:
  - Multiverse-Core
  - WorldEdit
authors: [ lorenzop ]
website: ${project.url}
description: ${project.description}
permissions:
    pxn.*:
        default: op
        description: Gives access to all pxn plugin lib commands.
        children:
            pxn.updates:           true
            pxn.cmd.help:          true
            pxn.cmd.list:          true
            pxn.cmd.home:          true
            pxn.cmd.tp.*:          true
            pxn.cmd.back:          true
            pxn.cmd.top:           true
            pxn.cmd.bottom:        true
            pxn.cmd.jump:          true
            pxn.cmd.motd:          true
            pxn.cmd.broadcast:     true
            pxn.cmd.msg:           true
            pxn.cmd.me:            true
            pxn.cmd.gm.*:          true
            pxn.cmd.feed:          true
            pxn.cmd.feed.other:    true
            pxn.cmd.heal:          true
            pxn.cmd.heal.other:    true
            pxn.cmd.rest:          true
            pxn.cmd.rest.other:    true
            pxn.cmd.speed.*:       true
            pxn.cmd.workbench:     true
            pxn.cmd.enderchest:    true
            pxn.cmd.powertool:     true
            pxn.cmd.backup:        true
            pxn.cmd.gc:            true
    pxn.cmd.tp.*:
        default: op
        description: Gives access to all /tp commands.
        children:
            pxn.cmd.tp:            true
            pxn.cmd.tp.here:       true
            pxn.cmd.tp.ask:        true
            pxn.cmd.tp.askhere:    true
            pxn.cmd.tp.allhere:    true
            pxn.cmd.tp.askallhere: true
    pxn.cmd.gm.*:
        default: op
        description: Gives access to /gm commands.
        children:
            pxn.cmd.gm:      true
            pxn.cmd.gm.c:    true
            pxn.cmd.gm.s:    true
            pxn.cmd.gm.a:    true
            pxn.cmd.gm.spec: true
    pxn.cmd.speed.*:
        default: op
        description: Gives access to /walkspeed and /flyspeed commands.
        children:
            pxn.cmd.speed:      true
            pxn.cmd.speed.walk: true
            pxn.cmd.speed.fly:  true
    pxn.updates:
        default: op
        description: Receive notices of plugin updates.
    pxn.cmd.help:
        default: true
        description: Allow the /help command.
    pxn.cmd.list:
        default: true
        description: Allow the /list command.
    pxn.cmd.home:
        default: true
        description: Allow the /home command.

    pxn.cmd.tp:
        default: op
        description: Allow the /tp command.
    pxn.cmd.tp.here:
        default: op
        description: Allow the /tp-here command.
    pxn.cmd.tp.ask:
        default: op
        description: Allow the /tp-ask command.
    pxn.cmd.tp.askhere:
        default: op
        description: Allow the /tp-ask-here command.
    pxn.cmd.tp.allhere:
        default: op
        description: Allow the /tp-all-here command.
    pxn.cmd.tp.askallhere:
        default: op
        description: Allow the /tp-ask-all-here command.
    pxn.cmd.tp.offline:
        default: op
        description: Allow the /tp-offline command.

    pxn.cmd.back:
        default: op
        description: Allow the /back command.
    pxn.cmd.top:
        default: op
        description: Allow the /top command.
    pxn.cmd.bottom:
        default: op
        description: Allow the /bottom command.

    pxn.cmd.jump:
        default: op
        description: Allow the /jump command.

    pxn.cmd.motd:
        default: true
        description: Allow the /motd command.
    pxn.cmd.broadcast:
        default: op
        description: Allow the /broadcast command.
    pxn.cmd.msg:
        default: true
        description: Allow the /msg command.
    pxn.cmd.me:
        default: true
        description: Allow the /me command.

    pxn.cmd.gm:
        default: op
        description: Allow the /gm command.
    pxn.cmd.gm.c:
        default: op
        description: Allow the /gmc command.
    pxn.cmd.gm.s:
        default: op
        description: Allow the /gms command.
    pxn.cmd.gm.a:
        default: op
        description: Allow the /gma command.
    pxn.cmd.gm.spec:
        default: op
        description: Allow the /gmspec command.

    pxn.cmd.feed:
        default: op
        description: Allow the /feed command.
    pxn.cmd.feed.other:
        default: op
        description: Allow the /feed <player> command.
    pxn.cmd.heal:
        default: op
        description: Allow the /heal command.
    pxn.cmd.heal.other:
        default: op
        description: Allow the /heal <player> command.
    pxn.cmd.rest:
        default: op
        description: Allow the /rest command.
    pxn.cmd.rest.other:
        default: op
        description: Allow the /rest <player> command.

    pxn.cmd.speed:
        default: op
        description: Allow the /speed command.
    pxn.cmd.speed.walk:
        default: op
        description: Allow the /walkspeed command.
    pxn.cmd.speed.fly:
        default: op
        description: Allow the /flyspeed command.

    pxn.cmd.workbench:
        default: op
        description: Allow the /workbench command.
    pxn.cmd.enderchest:
        default: op
        description: Allow the /enderchest command.

    pxn.cmd.powertool:
        default: op
        description: Allow the /powertool command.
    pxn.cmd.backup:
        default: op
        description: Allow the /backup command.
    pxn.cmd.gc:
        default: op
        description: Allow the /gc command.
